version: "3.7"

services:
  vertica:
    image: vertica/vertica-ce:latest
    container_name: vertica
    environment:
      VERTICA_PASSWORD: my_secure_password  # Replace with your password
    ports:
      - "5433:5433"  # Expose Vertica's default port
    volumes:
      - vertica_data:/data  # Persist data across container restarts
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "vsql -U dbadmin -w my_secure_password -c 'SELECT 1;'"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS: "True"  
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: "google-cloud-platform://?key_path=/opt/airflow/keys/gcp-service-account.json"
      TZ: Asia/Bangkok 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./keys:/opt/airflow/keys
      - ./requirements.txt:/opt/airflow/requirements.txt 
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               airflow db upgrade &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      TZ: Asia/Bangkok 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./sql:/opt/airflow/sql          
      - ./keys:/opt/airflow/keys
      - ./mock_data:/opt/airflow/mock_data
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               airflow db upgrade &&
               airflow scheduler"

  airflow-worker:
    image: apache/airflow:2.7.1
    container_name: airflow-worker
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      TZ: Asia/Bangkok 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./sql:/opt/airflow/sql         
      - ./keys:/opt/airflow/keys  
      - ./mock_data:/opt/airflow/mock_data
      - ./requirements.txt:/opt/airflow/requirements.txt 
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               airflow worker"

volumes:
  postgres_data:
  vertica_data:

